yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # импорт правил из приложения posts
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from django.db.models.constraints import UniqueConstraint

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        'Название',
        max_length=200
    )
    slug = models.SlugField(
        'Уникальный адрес',
        unique=True
    )
    description = models.TextField('Описание')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class PostImage(models.Model):
    post = models.ForeignKey(
        'Post',
        on_delete=models.CASCADE,
        related_name='image'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        null=True,
        help_text='Загрузите картинку'
    )


class Post(models.Model):
    text = models.TextField('Текст поста', help_text='Текст нового поста')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
    )
    created = models.DateTimeField(
        'Дата создания',
        auto_now_add=True,
        db_index=True
    )


    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='коментарий к посту',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор коментария'
    )
    text = models.TextField(
        'Текст коментария',
        help_text='Введите текст'
    )
    created = models.DateTimeField(
        'Дата создания',
        auto_now_add=True,
        db_index=True
    )


    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'

    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    class Meta:
        verbose_name = 'Подписка на автора'
        verbose_name_plural = 'Подписки на авторов'
        UniqueConstraint(fields=['user', 'author'], name='unique_follower')

    def __str__(self):
        return f'{self.author}'

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page


from .forms import PostForm, CommentForm
from .models import Follow, Group, Post, User
from .utils import pagination_pages, POSTS_PER_PAGE, SAVE_VALUE_IN_CACHE


@cache_page(SAVE_VALUE_IN_CACHE, key_prefix='index_page')
def index(request):
    posts = Post.objects.select_related('author', 'group')
    page_obj = pagination_pages(request, posts, POSTS_PER_PAGE)
    title = 'Последние обновления на сайте'
    template = 'posts/index.html'
    context = {
        'page_obj': page_obj,
        'title': title
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author', 'group')
    page_obj = pagination_pages(request, posts, POSTS_PER_PAGE)
    template = 'posts/group_list.html'
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    count = posts.count()
    page_obj = pagination_pages(request, posts, POSTS_PER_PAGE)
    template = 'posts/profile.html'
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user,
        author=author
    ).exists()
    context = {
        'author': author,
        'page_obj': page_obj,
        'count': count,
        'following': following
    }
    return render(request, template, context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    author = post.author
    count = author.posts.count()
    template = 'posts/post_detail.html'
    comments = post.comments.all()
    form = CommentForm()
    context = {
        'post': post,
        'count': count,
        'form': form,
        'comments': comments
    }
    return render(request, template, context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    template = 'posts/create_post.html'
    if form.is_valid():
        form = form.save(commit=False)
        form.author = request.user
        form.save()
        return redirect('posts:profile', form.author)
    context = {
        'form': form
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post.id)
    template = 'posts/create_post.html'
    is_edit = True
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    context = {
        'form': form,
        'is_edit': is_edit
    }
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post.id)
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post.id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = pagination_pages(request, posts, POSTS_PER_PAGE)
    template = 'posts/follow.html'
    context = {
        'page_obj': page_obj
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    # мы в модель Follow добавили UniqueConstrain, эта проверка еще акутальна?
    # или там ограничения, что не может быть двух одинаковых подписок?,
    # а про автор, не автор речи нет.
    # Спасибо!
    if request.user == author:
        return redirect('posts:profile', author)
    Follow.objects.get_or_create(
        user=request.user,
        author=author
    )
    return redirect('posts:profile', author)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(
        user=request.user,
        author=author
    ).delete()
    return redirect('posts:profile', author)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% load user_filters %}
{% block title %}
Новый пост 
{% endblock %}

{% block content %}
<main>
  <div class="container py-5">
   <div class="row justify-content-center"> 
   <div class="col-md-8 p-5">
    {% if form.errors %}
      {% for field in form %} 
        {% for error in field.errors %}            
          <div class="alert alert-danger">
            {{ error|escape }}
          </div>
        {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
          {{ error|escape }}
        </div>
      {% endfor %}
    {% endif %}
      {% if is_edit %}
      <h3> Редоктирование поста </h3> 
      {% else %}
      <h3> Добавить запись </h3>
      {% endif %}
                   
        <form actions=""{% url 'posts:post_create' %}"" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {%for field in form %}
        <div class="form-group row my-3 p-3">

        {{ field.label }}
        {{ field|addclass:'form-control' }}

        <small class="form-text text-muted">
        {{ field.help_text }}
        </small> 
        
       </div>  
        {% endfor %}

          <div class="d-flex justify-content-center">
            {% if is_edit %}
            <button type="submit" class="btn btn-warning">
              Сохранить
            </button>
            {% else %}
            <button type="submit" class="btn btn-primary">
              Добавить
            </button>
            {% endif %}  
          </div>
        </form>
    </div>
  </div>
</div>
</main>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}
  Посты избранных авторов
{% endblock %}


{% block content %}
<main> 
  <div class="container py-5">
    {% include 'posts/switcher.html' %} 
    {% for post in page_obj %}
      {% include 'posts/resulting_selection.html'%}
    {% if post.group %}   
    <br><a href="{% url 'posts:group_list' post.group.slug %}" class="btn btn-primary">все записи группы</a>
  {% endif %} 
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 
  </div>
<div class="col-md-6 offset-md-4">
{% include 'includes/paginator.html' %}
</div>
</main> 
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}
Записи сообщества: {{ group.title }}
{% endblock %}

{% block content %}
    <div class="container py-5"> 
    {% block header %} <h1> {{ group.title }} </h1> {% endblock %}
      <p> {{ group.description }} </p>
      {% for post in page_obj %}
        {% include 'posts/resulting_selection.html'%}
     <a href="{% url 'posts:group_list' post.group.slug %}" class="btn btn-primary">все записи группы</a>
       {% if not forloop.last %}<hr>{% endif %}
      {% endfor %} 
    </div>  
    <div class="col-md-6 offset-md-5">
      {% include 'includes/paginator.html' %}
    </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}
  {{ title }}
{% endblock %}


{% block content %}
<main> 
  <div class="container py-5">
    {% include 'posts/switcher.html' %} 
    {% for post in page_obj %}
      {% include 'posts/resulting_selection.html'%}
    {% if post.group %}   
    <br><a href="{% url 'posts:group_list' post.group.slug %}" class="btn btn-primary">все записи группы</a>
  {% endif %} 
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 
  </div>
<div class="col-md-6 offset-md-4">
{% include 'includes/paginator.html' %}
</div>
</main> 
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% load user_filters %}

{% block title %}
Пост {{ post|truncatechars:30 }}
{% endblock %}
  
{% block content %}
    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.created|date:"d E Y" }}
            </li>
            <!-- если у поста есть группа -->  
            {% if post.group %}
            <li class="list-group-item">
              Группа: {{ post.group }}
              <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
              </a>
            </li>
            {% endif %} 
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span > {{ count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
              <br>
              {% if post.author == request.user %}   
              <a href= "{% url 'posts:post_edit' post.id %}">
                редактировать запись
                {% endif %} 
              </a>       
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text }}</p>
        {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
          <form method="post" action="{% url 'posts:add_comment' post.id %}">
          {% csrf_token %}      
          <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
          </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
        </form>
       </div>
      </div>
      {% endif %}
      {% for comment in comments %}
      <div class="media mb-4">
        <div class="media-body">
        <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
        </h5>
        <p>
        {{ comment.text }}
        </p>
      </div>
     </div>
    {% endfor %}
    </article>
    </div> 
  </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}
Профайл пользователя {{author.get_full_name}}
{% endblock %}

{% block content %}
<main> 
  <div class="container py-5">
    <div class="mb-5">
  <h1>Все посты пользователя <span class="badge bg-primary"> {{ author.get_full_name }} </span></h1>
  <h3>Всего постов: {{count}} </h3>   
  {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
   {% endif %}
</div>
<article>
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{author.get_full_name}}
        <a 
          href="{% url 'posts:profile' post.author.username %}">все посты пользователя
         </a>
       </li>
        <li>
          Дата публикации: {{ post.created|date:"d E Y" }}
        </li>
    </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      {{ post.text }}
      <br> <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
      {% if post.group %}
        <br><a href="{% url 'posts:group_list' post.group.slug %}">
        все записи группы "{{post.group}}"</a>
      {% endif %} <br>   
      {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
  </article> 
    <div class="col-md-6 offset-md-4">
      {% include 'includes/paginator.html' %}
    </div>
</main>
{% endblock %}

yatube/templates/posts/resulting_selection.html
{% load thumbnail %}
<article>
<ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    <a 
      href="{% url 'posts:profile' post.author.username %}" class="btn btn-primary">
      все посты пользователя </a>
    </li>
    <li>
      Дата публикации: {{ post.created|date:"d E Y" }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img my-2" src="{{ post_postimage.url }}">
  {% endthumbnail %}
  <p>{{ post.text }}</p>
  <a href="{% url 'posts:post_detail' post.pk %}" class="btn btn-info">подробная информация</a> 
  <br>
</article> 

yatube/templates/posts/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}